export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Activity rows: explicit file edits emitted by edit tools. */
  fileEdits?: UIFileEdit[];
  /** Activity rows: structured tool lifecycle events used for status badges. */
  toolEvents?: ToolProgressEvent[];
  /** Activity rows: backend-authored turn checkpoint used for recoverable task snapshots. */
  checkpoint?: UITurnCheckpoint;
  /** Activity rows: backend-authored context/memory compression event. */
  contextCompaction?: UIContextCompaction;
  /** Activity rows: safe observability metadata for memory sources injected into context. */
  memorySnapshot?: UIMemorySnapshot;
  /** Activity rows: safe observability metadata for skills injected into context. */
  activeSkills?: UIActiveSkills;
  /** Activity rows: user-confirmable long-term memory candidate. */
  memoryCandidate?: UIMemoryCandidate;
  /** Activity rows created during the same agent phase share one collapsible block. */
  activitySegmentId?: string;
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "queued" | "start" | "running" | "end" | "error" | string;
  checkpoint_id?: string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  risk_category?:
    | "read"
    | "write"
    | "shell"
    | "network"
    | "mcp"
    | "tool"
    | string;
  risk_level?: "low" | "medium" | "high" | string;
  safety?: {
    category?: string;
    level?: string;
    blocked?: boolean;
    reason?: string;
    requires_sandbox?: boolean;
    [key: string]: unknown;
  };
  files?: unknown[];
  embeds?: unknown[];
  queued_at?: string;
  started_at?: string;
  completed_at?: string;
  elapsed_ms?: number;
  duration_ms?: number;
  batch_id?: string;
  batch_index?: number;
  batch_count?: number;
  batch_size?: number;
  concurrency_limit?: number;
  queue_position?: number;
  failure_category?: string;
  recovery_action?: string;
  retryable?: boolean;
  needs_user_input?: boolean;
  diagnostic_label?: string;
  diagnostic_hint?: string;
  recommended_action?: string;
  read_only?: boolean;
  concurrency_safe?: boolean;
  exclusive?: boolean;
  config_key?: string;
  scopes?: string[];
}

export type UITurnCheckpointCheckState =
  | "none"
  | "running"
  | "passed"
  | "failed"
  | string;

export interface UITurnCheckpoint {
  version?: number;
  checkpoint_id?: string | null;
  turn_id?: string;
  phase?: string;
  tool_call_count?: number;
  pending_tool_count?: number;
  completed_tool_count?: number;
  pending_tool_call_ids?: string[];
  completed_tool_call_ids?: string[];
  executed_tool_call_ids?: string[];
  reused_tool_call_ids?: string[];
  reused_tool_count?: number;
  compensation_tool_call_ids?: string[];
  compensation_tool_count?: number;
  retryable_tool_call_ids?: string[];
  retryable_tool_count?: number;
  requires_user_tool_call_ids?: string[];
  requires_user_tool_count?: number;
  resumable_tool_call_ids?: string[];
  resumable_tool_count?: number;
  recovered_executed_tool_call_ids?: string[];
  recovered_executed_tool_count?: number;
  recovered_skipped_tool_call_ids?: string[];
  recovered_skipped_tool_count?: number;
  recovered_requires_user_tool_call_ids?: string[];
  recovered_requires_user_tool_count?: number;
  safe_resume_tool_call_ids?: string[];
  safe_resume_tool_count?: number;
  review_required_tool_call_ids?: string[];
  review_required_tool_count?: number;
  needs_input_tool_call_ids?: string[];
  needs_input_tool_count?: number;
  blocked_tool_call_ids?: string[];
  blocked_tool_count?: number;
  recovery_review_items?: Array<{
    tool_call_id?: string;
    name?: string;
    group?: "safe_resume" | "review_required" | "needs_input" | "blocked" | string;
    reason?: string;
    recovery_action?: string;
    action_label?: string;
    review_kind?: string;
    summary?: string;
    config_key?: string;
    scope?: string;
    can_resume_now?: boolean;
    can_retry_now?: boolean;
    review_state?: string;
    status_label?: string;
    input_required?: boolean;
    input_placeholder?: string | null;
    review_confirmed?: boolean;
  }>;
  recovery_review_count?: number;
  skipped_duplicate_tool_call_ids?: string[];
  skipped_duplicate_tool_count?: number;
  last_tool_call_id?: string | null;
  file_edit_count?: number;
  check_state?: UITurnCheckpointCheckState;
  recoverable?: boolean;
  updated_at?: string;
  source?: "live" | "history" | "recovered" | string;
  recovered?: boolean;
  recovered_pending_tool_count?: number;
}

export interface UIContextCompaction {
  version?: number;
  reason?: "token_budget" | "replay_window" | "idle_ttl" | string;
  source?: "token_consolidator" | "auto_compact" | string;
  before_message_count?: number;
  after_message_count?: number;
  archived_message_count?: number;
  kept_message_count?: number;
  before_token_estimate?: number;
  after_token_estimate?: number;
  saved_token_estimate?: number;
  summary_token_estimate?: number;
  summary_preview?: string;
  summary_sections?: Record<string, string[]>;
  /** Full rendered markdown/text for structured sections (UI convenience). */
  summary_full?: string;
  token_source?: string;
  updated_at?: string;
}

export interface UIMemorySourceStats {
  included?: boolean;
  exists?: boolean;
  char_count?: number;
  token_estimate?: number;
  updated_at?: string | null;
  entry_count?: number;
}

export interface UIMemorySnapshot {
  version?: number;
  sources?: {
    memory?: UIMemorySourceStats;
    soul?: UIMemorySourceStats;
    user?: UIMemorySourceStats;
    recent_history?: UIMemorySourceStats;
    session_summary?: UIMemorySourceStats;
    [key: string]: UIMemorySourceStats | undefined;
  };
  retrieved?: {
    included?: boolean;
    entry_count?: number;
    categories?: Record<string, number>;
    reasons?: string[];
    items?: Array<{
      id?: string;
      source?: string;
      category?: string;
      reason?: string;
      safety?: string;
      updated_at?: string;
    }>;
  };
  updated_at?: string;
}

export interface UIActiveSkill {
  name?: string;
  source?: "always" | "auto" | "explicit" | string;
  matched_keywords?: string[];
  priority?: number;
  reason?: string;
}

export interface UIActiveSkills {
  version?: number;
  skills?: UIActiveSkill[];
  selection_limit?: number;
  updated_at?: string;
}

export type UIMemoryCandidateType =
  | "user_profile"
  | "project_memory"
  | "assistant_style"
  | string;

export interface UIMemoryCandidate {
  version?: number;
  id?: string;
  type?: UIMemoryCandidateType;
  target?: string;
  title?: string;
  content?: string;
  reason?: string;
  source?: string;
  turn_id?: string | null;
  assistant_preview?: string;
  sensitive?: boolean;
  duplicate?: boolean;
  existing_preview?: string;
  merge_action?: string;
  merge_reason?: string;
  conflict_reason?: string;
  merged_content?: string;
  merge_score?: number;
  created_at?: string;
}

export interface RecoveryActionResult {
  ok: boolean;
  checkpoint?: UITurnCheckpoint;
}

export interface MemoryCandidateCommitResult {
  committed: boolean;
  duplicate?: boolean;
  merged?: boolean;
  conflict?: boolean;
  duplicate_reason?: string;
  existing_preview?: string;
  merge_action?: string;
  merge_reason?: string;
  conflict_reason?: string;
  merged_content?: string;
  target?: string;
  candidate?: UIMemoryCandidate;
}

export interface UIFileEdit {
  version?: number;
  call_id: string;
  tool: string;
  path: string;
  absolute_path?: string;
  phase?: "start" | "end" | "error" | string;
  added: number;
  deleted: number;
  approximate?: boolean;
  status: "editing" | "done" | "error";
  binary?: boolean;
  error?: string;
  pending?: boolean;
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
  /** Unix epoch seconds when this session currently has a turn in flight. */
  runStartedAt?: number | null;
}

export type SidebarDensity = "comfortable" | "compact";
export type SidebarSortMode = "updated_desc" | "created_desc" | "title_asc";

export interface SidebarViewState {
  density: SidebarDensity;
  show_previews: boolean;
  show_timestamps: boolean;
  show_archived: boolean;
  sort: SidebarSortMode;
}

export interface SidebarStatePayload {
  schema_version: number;
  pinned_keys: string[];
  archived_keys: string[];
  title_overrides: Record<string, string>;
  tags_by_key: Record<string, string[]>;
  collapsed_groups: Record<string, boolean>;
  view: SidebarViewState;
  updated_at?: string | null;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
    model_preset: string | null;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    timezone: string;
    bot_name: string;
    bot_icon: string;
    tool_hint_max_length: number;
  };
  model_presets: Array<{
    name: string;
    label: string;
    active: boolean;
    is_default: boolean;
    model: string;
    provider: string;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
  }>;
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    api_key_required?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    max_results: number;
    timeout: number;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "base_url";
    }>;
  };
  web: {
    enable: boolean;
    proxy?: string | null;
    user_agent?: string | null;
    search: {
      max_results: number;
      timeout: number;
    };
    fetch: {
      use_jina_reader: boolean;
    };
  };
  image_generation: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_image_size: string;
    max_images_per_turn: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
  };
  runtime: {
    config_path: string;
    workspace_path: string;
    gateway_host: string;
    gateway_port: number;
    heartbeat: {
      enabled: boolean;
      interval_s: number;
      keep_recent_messages: number;
    };
    dream: {
      schedule: string;
      max_batch_size: number;
      max_iterations: number;
      annotate_line_ages: boolean;
    };
    unified_session: boolean;
  };
  advanced: {
    restrict_to_workspace: boolean;
    ssrf_whitelist_count: number;
    mcp_server_count: number;
    exec_enabled: boolean;
    exec_sandbox?: string | null;
    exec_path_append_set: boolean;
  };
  requires_restart: boolean;
  restart_required_sections?: Array<"runtime" | "web" | "image">;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
  modelPreset?: string | null;
  timezone?: string;
  botName?: string;
  botIcon?: string;
  toolHintMaxLength?: number;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
  maxResults?: number;
  timeout?: number;
  useJinaReader?: boolean;
}

export interface ImageGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultImageSize: string;
  maxImagesPerTurn: number;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tool_events?: ToolProgressEvent[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Optional structured payload on progress frames (channel-specific). */
      agent_ui?: AgentUIBlob;
    }
  | {
      event: "checkpoint";
      chat_id: string;
      checkpoint: UITurnCheckpoint;
    }
  | {
      event: "context_compaction";
      chat_id: string;
      compaction: UIContextCompaction;
    }
  | {
      event: "memory_snapshot";
      chat_id: string;
      snapshot: UIMemorySnapshot;
    }
  | {
      event: "active_skills";
      chat_id: string;
      skills: UIActiveSkills;
    }
  | {
      event: "memory_candidate";
      chat_id: string;
      candidate: UIMemoryCandidate;
    }
  | {
      event: "file_edit";
      chat_id: string;
      edits: UIFileEdit[];
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
    }
  | {
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
    }
  | {
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    }
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | {
      event: "session_updated";
      chat_id: string;
      scope?: "metadata" | "thread" | string;
    }
  | { event: "error"; chat_id?: string; detail?: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export interface OutboundImageGeneration {
  enabled: true;
  aspect_ratio?: string | null;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      image_generation?: OutboundImageGeneration;
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    };
